config/routes.rb
Schuster::Application.routes.draw do

  root :to => 'pages#index'
  resources :aktuelles

end

app/models/aktuelle.rb
class Aktuelle < ActiveRecord::Base

  has_many :aktuelle_translations
  mount_uploader :image, AktuelleImageUploader

  translates :title, :text
  accepts_nested_attributes_for :translations

  validates_presence_of :title

  def to_param
      "#{id}-#{title.parameterize}"
  end

end

app/models/aktuelle_translation.rb
class AktuelleTranslation < ActiveRecord::Base
  belongs_to :aktuelle
end

app/controllers/aktuelles_controller.rb
class AktuellesController < ApplicationController


  def index
    @aktuelles = Aktuelle.all
  end

  def show
    @aktuelle = Aktuelle.find(params[:id])
  end

  def new
    @aktuelle = Aktuelle.new
  end

  def create
    @aktuelle = Aktuelle.new(params[:aktuelle])
    if @aktuelle.save
      redirect_to @aktuelle, :notice => "Successfully created aktuelle."
    else
      render :action => 'new'
    end
  end

  def edit
    @aktuelle = Aktuelle.find(params[:id])
  end

  def update
    @aktuelle = Aktuelle.find(params[:id])
    if @aktuelle.update_attributes(params[:aktuelle])
      redirect_to @aktuelle, :notice  => "Successfully updated aktuelle."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @aktuelle = Aktuelle.find(params[:id])
    @aktuelle.destroy
    redirect_to aktuelles_url, :notice => "Successfully destroyed aktuelle."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  helper :layouts

  before_filter :set_locale


  def set_locale
    # update session if passed
    session[:locale] = params[:locale] if params[:locale]

    # set locale based on session or default
    I18n.locale = session[:locale] || I18n.default_locale
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layouts_helper.rb
module LayoutsHelper

  def title(page_title)
    content_for(:title) { h(page_title.to_s) }
  end

  def metadesc(meta_desc)
    content_for(:meta_description) { h(meta_desc.to_s) }
  end

  def  keywords(meta_key)
    content_for(:meta_keywords) { h(meta_key.to_s) }
  end

end

app/views/aktuelles/_form.html.erb
<%= simple_form_for @aktuelle,:html => { :multipart => true } do |f| %>

<%= f.submit (@aktuelle.new_record? ? "Eintragen" : "Speichern") %>
	<p>&nbsp;</p>

<div class="inputs">
    <%= f.input :image, :as => :file, :required => false, :label => if @aktuelle.image? then
    image_tag(@aktuelle.image.url(:thumb))
        else
    'Bild max 150kb'
    end%>

</div>

<p>&nbsp;</p>
<div class="inputs">

  <h2>Deutsch (default locale)</h2>
  <p><%= f.input :title %></p>
  <p><%= f.cktext_area :text, :skin=> 'kama', :toolbar=>'Easy', :height=>'400px' %></p>

  <h2>Englisch</h2>
  <%= f.globalize_fields_for(:en) do |g| %>
  <p><%= g.input :title %></p>
  <p><%= g.cktext_area :text, :skin=> 'kama', :toolbar=>'Easy', :height=>'400px' %></p>
  <% end %>

</div>

<% end %>

app/views/aktuelles/edit.html.erb
<% title "Edit Aktuelle" %>

<%= javascript_include_tag "/javascripts/ckeditor/ckeditor.js" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @aktuelle %> |
  <%= link_to "View All", aktuelles_path %>
</p>

app/views/aktuelles/index.html.erb
<% title "Aktuelles" %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
  <% for aktuelle in @aktuelles %>
    <tr>
      <td><%= aktuelle.title %></td>
      <td><%= aktuelle.text %></td>
      <td><%= link_to "Show", aktuelle %></td>
      <td><%= link_to "Edit", edit_aktuelle_path(aktuelle) %></td>
      <td><%= link_to "Destroy", aktuelle, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Aktuelle", new_aktuelle_path %></p>

app/views/aktuelles/new.html.erb
<% title "New Aktuelle" %>

<%= javascript_include_tag "/javascripts/ckeditor/ckeditor.js" %>

<%= render 'form' %>

<p><%= link_to "Back to List", aktuelles_path %></p>

app/views/aktuelles/show.html.erb
<% title "Aktuelle" %>

<p>
  <strong>Title:</strong>
  <%= @aktuelle.title %>
</p>
<p>
  <strong>Text:</strong>
  <%= @aktuelle.text %>
</p>

<p>
  <%= link_to "Edit", edit_aktuelle_path(@aktuelle) %> |
  <%= link_to "Destroy", @aktuelle, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", aktuelles_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
  <title><%= content_for?(:title) ? yield(:title) : "Hotel Schuster" %></title>
  <meta name="description" content="<%= yield :meta_description %>" />
  <meta name="keywords" content="<%= yield :meta_keywords %>" />
  <meta name="robots" content="index, follow">

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>

  <link rel="icon" href="images/favicon.ico" type="image/ico" />

  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">

<div id="header">
  head
</div>


<div id="sidebar-left" class="clear">
  sidebar left
</div>

<div id="container">

<div id="sidebar-right">
  sidebar right
</div>

<div id="inhalte">
  <%= yield %>
</div>

</div><!--container ende-->

<div id="footer">footer</div>

</div><!--wrapper ende-->



</body>
</html>

app/views/pages/index.html.erb
<% title 'sample app globalize3'%>
<% metadesc "descriptions" %>
<% keywords "keywords" %>



<h1>1060 px breit</h1>

<p>The purpose of this HTML is to help determine what default settings are with CSS and to make sure that all possible HTML Elements are included in this HTML so as to not miss any possible Elements when designing a site.</p>

<hr />

<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>
<h4>Heading 4</h4>
<h5>Heading 5</h5>
<h6>Heading 6</h6>

<p>Lorem ipsum dolor sit amet, <a href="#" title="test link">test link</a> adipiscing elit. Nullam dignissim convallis est. Quisque aliquam. Donec faucibus. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam libero nisi, imperdiet at, tincidunt nec, gravida vehicula, nisl. Praesent mattis, massa quis luctus fermentum, turpis mi volutpat justo, eu volutpat enim diam eget metus. Maecenas ornare tortor. Donec sed tellus eget sapien fringilla nonummy. Mauris a ante. Suspendisse quam sem, consequat at, commodo vitae, feugiat in, nunc. Morbi imperdiet augue quis tellus.</p>

<hr />

<p>kleiner Abstand z.&thinsp;B.</p>
<p>weiche Trennung hierstehtein&shy;langesword</p>
<p>so könntes klappen &hellip;</p>
<p>&bdquo;Eiriseididum&ldquo;

<a href="#" class="pdf">PDF-Datei</a>


<h1 id="list_types">List Types</h1>

<h3>Definition List</h3>
<dl>
  <dt>Definition List Title</dt>
  <dd>This is a definition list division.</dd>
</dl>

<h3>Ordered List</h3>
<ol>
  <li>List Item 1</li>
  <li>List Item 2</li>
  <li>List Item 3</li>
</ol>

<h3>Unordered List</h3>
<ul>
  <li>List Item 1</li>
  <li>List Item 2</li>
  <li>List Item 3</li>
</ul>

<table cellspacing="0" cellpadding="0">
<tr><th>Table Header 1</th><th>Table Header 2</th><th>Table Header 3</th></tr>
<tr><td>Division 1</td><td>Division 2</td><td>Division 3</td></tr>
<tr class="even"><td>Division 1</td><td>Division 2</td><td>Division 3</td>
</tr><tr><td>Division 1</td><td>Division 2</td><td>Division 3</td></tr>
</table>

<small><a href="#wrapper">[top]</a></small>
<hr />